<?php
$retArr = [];
/////////////////////
///////运营数据//////
/////////////////////
$retArr['operate']                      = [];
$retArr['operate']['booking']['detail'] = [
    'OrderId'          => '订单号',
    'OrderVisitDate'   => '下单时间',
    'OrderConfirmDate' => '预约日期',
    'CityName'         => '区域',
    'ShopName'         => '门店',
    'DoctorName'       => '医生',
    'PatientName'      => '患者姓名',
    'MobilePhone'      => '患者号码',
    'OrderStatus'      => '到店状态',
    'OrderType'        => '订单类型',
    'SourceId'         => '来源',
    'PayStatus'        => '支付状态',
    'PayType'          => '支付类型',
    'FirstVisitFlag'   => '来访状态',
];
$retArr['operate']['online'] = [];
$retArr['operate']['online'] = [
    'kpi'  => [
        'Source_Id'          => '渠道ID',
        'Source_Name'        => '渠道名称',
        'Order_Sum'          => '预约量',
        'First_Order_Sum'    => '线上首诊',
        'First_Order_Rate'   => '首诊占比',
        'Further_Order_Sum'  => '线上复诊',
        'Further_Order_Rate' => '预约占比',
    ],
    'rate' => [
        'Source_Id'         => '渠道ID',
        'Source_Name'       => '渠道名称',
        'Order_Sum'         => '线上预约量',
        'Cancel_Order_Sum'  => '线上取消量',
        'Miss_Order_Sum'    => '线上爽约量',
        'Cancel_Order_Rate' => '预约取消率',
        'Miss_Order_Rate'   => '预约爽约率',
    ],

];
$retArr['operate']['doctor']              = [];
$retArr['operate']['doctor']['KPIDaySum'] = [
    'Sum_Date'         => '日期',
    'City_Name'        => '区域',
    'Shop_Name'        => '门店',
    'Doctor_MisId'     => 'Mis ID',
    'Doctor_Name'      => '医生名字',
    'Total_Counts'     => '放号量',
    'OutPatientNum'    => '门诊量',
    'FirstVisitNum'    => '首诊量',
    'OrderOnlineNum'   => '线上预约量',
    'FirstVisitOnline' => '线上首诊量',
    'mzyy_rate'        => '线上预约率',
    'mzsz_rate'        => '线上首诊率',
    'Saturation'       => '饱和度',
    'Doctor_Level'     => '级别',

];
$retArr['operate']['doctor']['KPIWeekSum'] = [
    'Sum_Date'         => '周期',
    'City_Name'        => '区域',
    'Shop_Name'        => '门店',
    'Doctor_MisId'     => 'Mis ID',
    'Doctor_Name'      => '医生名字',
    'Total_Counts'     => '放号量',
    'OutPatientNum'    => '门诊量',
    'FirstVisitNum'    => '首诊量',
    'OrderOnlineNum'   => '线上预约量',
    'FirstVisitOnline' => '线上首诊量',
    'mzyy_rate'        => '线上预约率',
    'mzsz_rate'        => '线上首诊率',
    'Saturation'       => '饱和度',
    'Doctor_Level'     => '级别',

];
$retArr['operate']['doctor']['KPIMonthSum'] = [
    'Sum_Date'         => '月份',
    'City_Name'        => '区域',
    'Shop_Name'        => '门店',
    'Doctor_MisId'     => 'Mis ID',
    'Doctor_Name'      => '医生名字',
    'Total_Counts'     => '放号量',
    'OutPatientNum'    => '门诊量',
    'FirstVisitNum'    => '首诊量',
    'OrderOnlineNum'   => '线上预约量',
    'FirstVisitOnline' => '线上首诊量',
    'mzyy_rate'        => '线上预约率',
    'mzsz_rate'        => '线上首诊率',
    'Saturation'       => '饱和度',
    'Doctor_Level'     => '级别',

];
$retArr['operate']['doctor']['RankWeekSum'] = [
    'Sum_Date'                  => '周期',
    'City_Name'                 => '区域',
    'Shop_Name'                 => '门店',
    'Doctor_Name'               => '医生名字',
    'rank'                      => '预约排行',
    'Doctor_Level'              => '级别',
    'OutPatientNum'             => '个人门诊量',
    'OutPatientNum_Rate'        => '门店占比',
    'FirstVisitNum'             => '首诊量',
    'FirstVisitNum_Rate'        => '门店占比',
    'OrderOnlineNum'            => '个人预约量',
    'ShopOrderOnlineNum_Rate'   => '门店占比',
    'ShopFirstVisitOnline_Rate' => '预约率',
    'FirstVisitOnline'          => '首诊占比',
];
$retArr['operate']['doctor']['RankMonthSum'] = [
    'Sum_Date'                  => '月份',
    'City_Name'                 => '区域',
    'Shop_Name'                 => '门店',
    'Doctor_Name'               => '医生名字',
    'rank'                      => '预约排行',
    'Doctor_Level'              => '级别',
    'OutPatientNum'             => '个人门诊量',
    'OutPatientNum_Rate'        => '门店占比',
    'FirstVisitNum'             => '首诊量',
    'FirstVisitNum_Rate'        => '门店占比',
    'OrderOnlineNum'            => '个人预约量',
    'ShopOrderOnlineNum_Rate'   => '门店占比',
    'ShopFirstVisitOnline_Rate' => '预约率',
    'FirstVisitOnline'          => '首诊占比',
];
$retArr['operate']['shop']['KPIDaySum'] = [
    'Sum_Date'             => '日期',
    'City_Name'            => '区域',
    'Shop_Name'            => '门店',
    'Total_Counts'         => '放号量',
    'OutPatientNum'        => '门诊量',
    'FirstVisitNum'        => '首诊量',
    'OrderOnlineNum'       => '预约量',
    'FirstVisitOnline'     => '首诊量',
    'OrderOnlineRate'      => '门诊预约率',
    'FirstVisitOnlineRate' => '首诊预约率',
];
$retArr['operate']['shop']['KPIWeekSum'] = [
    'Sum_Date'               => '日期',
    'City_Name'              => '区域',
    'Shop_Name'              => '门店',
    'Total_Counts'           => '放号量',
    'OutPatientNum'          => '门诊量',
    'FirstVisitNum'          => '首诊量',
    'OrderOnlineNum'         => '预约量',
    'FirstVisitOnline'       => '首诊量',
    'OrderOnlineRate'        => '门诊预约率',
    'FirstVisitOnlineRate'   => '首诊预约率',
    'OrderOnlineRate_a'      => '线上预约占比-A',
    'OrderOnlineRate_b'      => '线上预约占比-B',
    'OrderOnlineRate_c'      => '线上预约占比-C',
    'FirstVisitOnlineRate_a' => '线上首诊占比-A',
    'FirstVisitOnlineRate_b' => '线上首诊占比-B',
    'FirstVisitOnlineRate_c' => '线上首诊占比-C',
];
$retArr['operate']['shop']['KPIMonthSum'] = [
    'Sum_Date'               => '日期',
    'City_Name'              => '区域',
    'Shop_Name'              => '门店',
    'Total_Counts'           => '放号量',
    'OutPatientNum'          => '门诊量',
    'FirstVisitNum'          => '首诊量',
    'OrderOnlineNum'         => '预约量',
    'FirstVisitOnline'       => '首诊量',
    'OrderOnlineRate'        => '门诊预约率',
    'FirstVisitOnlineRate'   => '首诊预约率',
    'OrderOnlineRate_a'      => '线上预约占比-A',
    'OrderOnlineRate_b'      => '线上预约占比-B',
    'OrderOnlineRate_c'      => '线上预约占比-C',
    'FirstVisitOnlineRate_a' => '线上首诊占比-A',
    'FirstVisitOnlineRate_b' => '线上首诊占比-B',
    'FirstVisitOnlineRate_c' => '线上首诊占比-C',
];
$retArr['qrcode']['qrcode']['doctor'] = [
    'daily'   => [
        'Date'        => '日期',
        'Doctor_Id'   => '医生ID',
        'Doctor_Name' => '医生名称',
        'City_Name'   => '区域',
        'Shop_Name'   => '门店',
        'New_Scan'    => '扫码净增次数',
        'New_Scan_v'  => '扫码净增变动值',
        'Scan'        => '累计扫码次数',
        'Scan_v'      => '累计扫码次数变动值',
        'Follow'      => '累计关注数',
        'Follow_v'    => '累计关注数变动值',
    ],
    'weekly'  => [
        'date'        => '周期',
        'doctor_id'   => '医生ID',
        'doctor_name' => '医生名称',
        'new_scan'    => '扫码新用户人数',
        'new_scan_v'  => '新用户-变动值',
        'scan_v'      => '累计扫码用户总人数',
        'follow_v'    => '累计 - 变动值',
    ],
    'monthly' => [
        'date'        => '月份',
        'doctor_id'   => '医生ID',
        'doctor_name' => '医生名称',
        'new_scan'    => '扫码新用户人数',
        'new_scan_v'  => '新用户-变动值',
        'scan_v'      => '累计扫码用户总人数',
        'follow_v'    => '累计 - 变动值',
    ],

];
$retArr['qrcode']['qrcode']['shop'] = [
    'daily'   => [
        'Date'       => '日期',
        'Shop_Id'    => '门店ID',
        'City_Name'  => '区域',
        'Shop_Name'  => '门店',
        'New_Scan'   => '扫码净增次数',
        'New_Scan_v' => '扫码净增变动值',
        'Scan'       => '累计扫码次数',
        'Scan_v'     => '累计扫码次数变动值',
        'Follow'     => '累计关注数',
        'Follow_v'   => '累计关注数变动值',
    ],
    'weekly'  => [
        'date'       => '周期',
        'shop_id'    => '门店ID',
        'shop_name'  => '门店名称',
        'new_scan'   => '扫码新用户人数',
        'new_scan_v' => '新用户-变动值',
        'scan_v'     => '累计扫码用户总人数',
        'follow_v'   => '累计 - 变动值',
    ],
    'monthly' => [
        'date'       => '月份',
        'shop_id'    => '门店ID',
        'shop_name'  => '门店名称',
        'new_scan'   => '扫码新用户人数',
        'new_scan_v' => '新用户-变动值',
        'scan_v'     => '累计扫码用户总人数',
        'follow_v'   => '累计 - 变动值',
    ],

];
$retArr['qrcode']['qrcode']['city'] = [
    'daily'   => [
        'Date'       => '日期',
        'City_Id'    => '区域ID',
        'City_Name'  => '区域',
        'New_Scan'   => '扫码净增次数',
        'New_Scan_v' => '扫码净增变动值',
        'Scan'       => '累计扫码次数',
        'Scan_v'     => '累计扫码次数变动值',
        'Follow'     => '累计关注数',
        'Follow_v'   => '累计关注数变动值',
    ],
    'weekly'  => [
        'date'       => '周期',
        'shop_id'    => '区域ID',
        'shop_name'  => '区域名称',
        'new_scan'   => '扫码新用户人数',
        'new_scan_v' => '新用户-变动值',
        'scan_v'     => '累计扫码用户总人数',
        'follow_v'   => '累计 - 变动值',
    ],
    'monthly' => [
        'date'       => '月份',
        'shop_id'    => '区域ID',
        'shop_name'  => '区域名称',
        'new_scan'   => '扫码新用户人数',
        'new_scan_v' => '新用户-变动值',
        'scan_v'     => '累计扫码用户总人数',
        'follow_v'   => '累计 - 变动值',
    ],

];
$retArr['qingchat']['doctor']['kpi'] = [
    'Stat_time'               => '日期',
    'Doctor_Num'              => '问诊医生量',
    'Online_ChatNum'          => '总问诊量',
    'Online_AnswerNum'        => '24H回复咨询量',
    'TowHourAnswerNum'        => '2小时回复咨询量',
    'First_AnswerDoctorNum'   => '每天新增首次回复医生量',
    'TwoWeek_AnswerDoctorNum' => '两周内有回复医生量',
    'LeiJi_NewDoctorNum'      => '当日新增问诊医生量',
    'ChangeToFans_Num'        => '当日挂号粉丝转换量',
    'ChatToApp_Num'           => '当日问诊预约转化量',
    'LeiJi_AppNum'            => '累计问诊预约转化量',
    'LeiJi_DoctorNum'         => '累计问诊医生量',
    'LeiJi_ChatNum'           => '累计总问诊量',
    'LeiJi_ToFansNum'         => '累计挂号粉丝转换量',
];
$retArr['qingchat']['city']['scan'] = [
    'Insert_Date'         => '统计日期',
    'City_Id'             => '区域ID',
    'City_Name'           => '区域',
    'NewFans_Num'         => '当日新增粉丝数',
    'LeiJi_FansNum'       => '当月粉丝数',
    'Today_Qrcode_Num'    => '当日开通二维码人数',
    'LeiJi_Qrcode_Num'    => '累计开通二维码人数(系统上线至今)',
    'Today_NewScan_Num'   => '当日净增扫码量',
    'LeiJi_Scan_Num'      => '累计扫码量',
    'Month_New_Scan'      => '当月净增扫码量',
    'KT_QingChart_Num'    => '开通轻问诊人数',
    'Today_EffectAsk_Num' => '日有效问题净增量',
    'LeiJi_EffectAsk_Num' => '有效问题累计量',
];
$retArr['financial']['shop']            = [];
$retArr['financial']['shop']['operate'] = [
    'City_Name'=>'区域',
    'Shop_Name'=>'门店名称',
    'Reg_Num'=>'挂号人次',
    'Patient_Num'=>'就诊人数',
    'PaoDan_Num'=>'跑单人次',
    'Qrcode_Num'=>'扫码人数',
    'Qrcode_Per'=>'扫码关注占比',
    'Return_Num'=>'回诊人数',
    'Return_Per'=>'回诊率',
    'XieDingFang_Num'=>'协定方处方量',
    'YinPian_Num'=>'中药饮片处方数量',
    'WeiXin_Num'=>'微信预约人数',
    'WeiXin_Per'=>'微信预约率',
    'Wait_DrugsTime'=>'高峰候药时间(分钟)',
    'Wait_FeeTime'=>'高峰期收费等候时间',
    'Wait_PayTime'=>'高峰收费时间',
    'ShuangYue_Num'=>'爽约人次',
    'ShuangYue_Per'=>'爽约率',
    'DaiJian_Num'=>'代煎处方量',
    'DaiJian_Per'=>'代煎代寄占比',
];
return $retArr;
